import os
import logging

logging.basicConfig(
    format = u'%(filename)s[LINE:%(lineno)d]# %(levelname)-8s [%(asctime)s]  %(message)s',
    level = logging.ERROR
)

# Base path to directory with data
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(BASE_DIR, 'data')

# Path to directory with embeddings files for each supported language
LANGS_EMBEDDINGS = os.path.join(DATA_DIR, 'word2vec_emb')
# path to multilang embeddings array
WORD2VEC_EMBEDDINGS = os.path.join(DATA_DIR, 'embeddings.pickle')
# path to multilang vocabulary dict (word: index in embeddings)
VOCABULARY_PATH = os.path.join(DATA_DIR, 'vocabulary.json')

MODELS_DIR_PATH = os.path.join(BASE_DIR, 'models')
# path to trained model in .h5py format
MODEL_PATH = os.path.join(MODELS_DIR_PATH, 'trained_model.h5py')

# Length of each document field (common length)
TITLES_PAD = 10
KEYWORDS_PAD = 18
DESCRIPTION_PAD = 18
TEXT_PAD = 134
# Number of labels and dict of labels
LABEL_NUMBER = 2
# Label dict
IDX_LABEL = {
    0: 'Normal',
    1: 'Adult'
}

# Stopwords for all supporting languages
STOPWORDS = {
    'tr': ['acaba', 'ama', 'aslında', 'az', 'bazı', 'belki', 'biri', 'birkaç',
           'birşey', 'biz', 'bu', 'çok', 'çünkü', 'da', 'daha', 'de',
           'defa',
           'diye', 'eğer', 'en', 'gibi', 'hem', 'hep', 'hepsi', 'her',
           'hiç',
           'için', 'ile', 'ise', 'kez', 'ki', 'kim', 'mı', 'mu', 'mü',
           'nasıl',
           'ne', 'neden', 'nerde', 'nerede', 'nereye', 'niçin', 'niye', 'o',
           'sanki', 'şey', 'siz', 'şu', 'tüm', 've', 'veya', 'ya', 'yani'],
    'pt': ['estiveram', 'estão', 'te', 'tivermos', 'nos', 'tua', 'estes',
           'estivesse', 'tém', 'tivessem', 'fui', 'temos', 'teremos',
           'isto',
           'estiverem', 'às', 'lhes', 'houveríamos', 'seríamos', 'tinham',
           'era', 'tinha', 'foram', 'for', 'mais', 'tivéssemos', 'nossa',
           'quando', 'me', 'estivemos', 'como', 'aquelas', 'sua', 'tivemos',
           'ou', 'muito', 'formos', 'aquele', 'tenho', 'as', 'está',
           'estamos',
           'fôssemos', 'num', 'em', 'hajam', 'isso', 'estiver', 'pelo',
           'seja',
           'esteja', 'houver', 'houverá', 'nós', 'havemos', 'hão', 'no',
           'serei', 'houvemos', 'tuas', 'eles', 'aquilo', 'serão', 'os',
           'para', 'por', 'também', 'pelos', 'houveram', 'tenha', 'tiverem',
           'houveria', 'tivera', 'até', 'essa', 'estivermos', 'seremos',
           'tínhamos', 'tiver', 'ela', 'estávamos', 'seriam', 'houvesse',
           'estavam', 'fosse', 'nas', 'estivéssemos', 'éramos', 'teríamos',
           'são', 'depois', 'vocês', 'na', 'estou', 'uma', 'esses', 'fomos',
           'o', 'quem', 'aqueles', 'houveriam', 'tive', 'tem', 'eu', 'das',
           'sejam', 'terei', 'será', 'seria', 'ao', 'essas', 'fôramos',
           'tivéramos', 'aos', 'à', 'este', 'forem', 'com', 'dos', 'sou',
           'se',
           'de', 'eram', 'estive', 'do', 'houve', 'a', 'esse', 'que', 'tu',
           'não', 'esta', 'somos', 'teria', 'pela', 'seu', 'haja', 'teu',
           'deles', 'estas', 'foi', 'teve', 'estivessem', 'estivéramos',
           'mesmo', 'houvera', 'terá', 'sem', 'ele', 'hei', 'meus', 'um',
           'tenhamos', 'teus', 'mas', 'minhas', 'numa', 'delas',
           'houvermos',
           'nossos', 'e', 'nosso', 'estejamos', 'fossem', 'estivera', 'só',
           'meu', 'houverão', 'teriam', 'fora', 'houverei', 'minha', 'da',
           'houverem', 'tivesse', 'seus', 'já', 'nossas', 'tenham', 'pelas',
           'terão', 'elas', 'estejam', 'suas', 'hajamos', 'houvéssemos',
           'esteve', 'entre', 'houveremos', 'aquela', 'sejamos', 'você',
           'dela', 'estava', 'dele', 'houvessem', 'tiveram', 'há', 'nem',
           'vos', 'houvéramos', 'qual', 'lhe'],
    'ru': ['их', 'мой', 'под', 'между', 'ничего', 'нельзя', 'один', 'какой',
           'будто', 'него', 'потом', 'им', 'себя', 'тем', 'даже', 'много',
           'по', 'тебя', 'ему', 'был', 'на', 'кто', 'чтобы', 'этого',
           'потому',
           'можно', 'есть', 'два', 'при', 'меня', 'уже', 'над', 'этот',
           'они',
           'для', 'он', 'быть', 'в', 'тогда', 'было', 'бы', 'вдруг', 'или',
           'всего', 'во', 'мы', 'ты', 'чем', 'этой', 'чего', 'от', 'и', 'ж',
           'до', 'совсем', 'из', 'такой', 'всегда', 'наконец', 'эту',
           'через',
           'там', 'нее', 'ней', 'ним', 'раз', 'тот', 'какая', 'сейчас',
           'только', 'тоже', 'ли', 'того', 'моя', 'хорошо', 'здесь', 'ну',
           'если', 'без', 'чтоб', 'разве', 'вы', 'надо', 'а', 'все',
           'другой',
           'за', 'были', 'лучше', 'этом', 'конечно', 'не', 'чуть', 'я', 'к',
           'почти', 'впрочем', 'всю', 'с', 'сам', 'вам', 'опять', 'них',
           'уж',
           'том', 'больше', 'как', 'будет', 'но', 'хоть', 'мне', 'перед',
           'ведь', 'после', 'еще', 'вас', 'себе', 'никогда', 'да', 'может',
           'теперь', 'у', 'об', 'что', 'то', 'ей', 'нас', 'она', 'его',
           'так',
           'куда', 'когда', 'же', 'вот', 'где', 'зачем', 'была', 'со',
           'иногда', 'нибудь', 'три', 'тут', 'более', 'всех', 'о', 'про',
           'свою', 'ни', 'эти', 'нет', 'ее'],
    'cs': ['ná', 'te', 'asi', 'článku', 'takze', 'prvni', 'jeho', 're',
           'než',
           'zprava', 'zde', 'polozka', 'kde', 'tvůj', 'což', 'váš',
           'články',
           'kdyz', 'jsme', 'kteri', 'mě', 'nebo', 'právě', 'ano', 'ta',
           'tvuj',
           'cz', 'pro', 'byt', 'tyto', 'me', 'dalsi', 'kdo', 'jak', 'pouze',
           'ni', 'pred', 'pri', 'již', 'témata', 'mezi', 'tak', 'téma',
           'temata', 'ptát', 've', 'zprávy', 'zpravy', 'článek', 'uz',
           'tím',
           'ktere', 'mate', 'ní', 'by', 's', 'mnou', 'jiz', 'aniz', 'podle',
           'proc', 'vsak', 'nasi', 'zpráv', 'jsou', 'nam', 'kterou', 'zpět',
           'však', 'napište', 'všechen', 'kazdy', 'bez', 'jako', 'přede',
           'vice', 'za', 'toho', 'ptat', 'tuto', 'ji', 'pres', 'prispevku',
           'aj', 'svym', 'tématy', 'take', 'z', 'nám', 'diskuse', 'jen',
           'vsechen', 'nad', 'ku', 'příspěvky', 'tom', 'nez', 'nechť',
           'clanek', 'pokud', 'ze', 'nas', 'které', 'neni', 'není',
           'příspěvku', 'tomto', 'ani', 'polozky', 'ještě', 'tento', 'on',
           'jeste', 'k', 'my', 'novy', 'tématem', 'timto', 'tedy', 'tato',
           'na', 'ten', 'tematu', 'mít', 'o', 'proč', 'přes', 'nový',
           'forum',
           'mi', 'prispevky', 'tematy', 'ptá', 'této', 'také', 'fóra',
           'svým',
           'bude', 'vy', 'jej', 'zpet', 'bylo', 'takže', 'mne', 'tímto',
           'tématu', 'ma', 'kteří', 'prispevek', 'tohoto', 'toto', 'článků',
           'nove', 'tipy', 'při', 'ja', 'se', 'svych', 'tematem', 'témat',
           'jenž', 'co', 'vas', 'své', 'od', 'do', 'pod', 'položky', 'a',
           'protože', 'který', 'ho', 'pak', 'prave', 'strana', 'té', 'tu',
           'vam', 'zda', 'coz', 'i', 'ke', 'dnes', 'po', 'že', 'muj', 'či',
           'tema', 'každý', 'další', 'jses', 'být', 'aniž', 'když', 'ktery',
           'má', 'naši', 'vase', 'svými', 'můj', 'příspěvek', 'jine', 'pta',
           'jste', 'ty', 'ale', 'svůj', 'máte', 'tim', 'jenz', 'těma',
           'jseš',
           'az', 'jsem', 'před', 'si', 'jejich', 'nic', 'vám', 'tomuto',
           'ci',
           'může', 'jí', 'svymi', 'budes', 'až', 'teto', 'to', 'fora',
           'příspěvků', 'v', 'první', 'proto', 'vaše', 'já', 'ktera', 'ne',
           'více', 'její', 'nové', 'položka', 'byl', 'clanky', 'prede',
           'ode',
           'muze', 'sice', 'u', 'byla', 'zprav', 'byli', 'fórum', 'mit',
           'nejsou', 'svuj', 'temat', 'budeš', 'necht', 'aby', 'je',
           'která',
           'náš', 'protoze', 'sve', 'už', 'diskuze', 'kam', 'budem', 'mně',
           'svých', 'tohle', 'zpráva', 'jeji', 'clanku', 'jiné', 'napiste'],
    'fr': ['eussiez', 'te', 'nos', 'au', 'qu', 'n', 'fut', 'avait', 'm',
           'son',
           'ayants', 'mon', 'êtes', 'ta', 'mes', 'étée', 'me', 'tes',
           'aient',
           'aurions', 'ai', 'leur', 'ou', 'as', 'aies', 'été', 'serai', 's',
           'elle', 'fûmes', 'pas', 'fussions', 'eût', 'étant', 'moi', 'un',
           'aviez', 't', 'ces', 'étais', 'auras', 'c', 'étés', 'était',
           'étaient', 'soient', 'eurent', 'eus', 'avez', 'par', 'furent',
           'ont', 'fus', 'le', 'fûtes', 'serions', 'soyons', 'notre',
           'eues',
           'on', 'du', 'dans', 'nous', 'l', 'fût', 'serait', 'ce', 'auront',
           'avons', 'd', 'eu', 'votre', 'auriez', 'ses', 'fusse', 'même',
           'pour', 'sommes', 'eut', 'et', 'à', 'avaient', 'ayantes', 'aura',
           'ma', 'sont', 'aie', 'aurait', 'eussent', 'se', 'est', 'vous',
           'de',
           'avais', 'étants', 'ait', 'sois', 'toi', 'tu', 'que', 'en',
           'soyez',
           'aurez', 'étées', 'ayant', 'avions', 'lui', 'avec', 'seront',
           'ayante', 'sur', 'serez', 'es', 'aux', 'il', 'ayons', 'étante',
           'étantes', 'eûtes', 'suis', 'seras', 'auraient', 'eûmes',
           'seraient', 'eussions', 'aurai', 'fusses', 'eusse', 'des', 'ne',
           'eux', 'aurons', 'ton', 'fussent', 'eusses', 'serons', 'serais',
           'fussiez', 'qui', 'sera', 'j', 'je', 'la', 'étiez', 'ayez',
           'aurais', 'étions', 'vos', 'y', 'une', 'sa', 'soit', 'eue',
           'mais',
           'seriez'],
    'de': ['meinen', 'deines', 'jenen', 'seiner', 'eurer', 'denselben',
           'einen', 'soll', 'jene', 'allem', 'einigem', 'demselben',
           'manchen',
           'denn', 'etwas', 'sie', 'im', 'muss', 'manche', 'anderr', 'ihm',
           'ohne', 'zum', 'unsem', 'solchem', 'wie', 'dieselbe', 'einige',
           'hinter', 'eure', 'daß', 'auf', 'sich', 'damit', 'kann', 'unser',
           'eines', 'dieses', 'einig', 'deine', 'gegen', 'keinem',
           'dieselben',
           'ihrem', 'auch', 'dann', 'eine', 'dein', 'seinen', 'welcher',
           'wieder', 'der', 'sondern', 'ihrer', 'warst', 'während',
           'wollte',
           'eurem', 'derselbe', 'wir', 'weg', 'anderen', 'seinem', 'können',
           'keine', 'meine', 'jedem', 'will', 'indem', 'diesen', 'über',
           'wenn', 'was', 'seine', 'nur', 'euren', 'ins', 'manches', 'kein',
           'unter', 'seines', 'ein', 'wirst', 'nichts', 'ihnen', 'als',
           'anders', 'jetzt', 'würde', 'war', 'sein', 'zur', 'aller',
           'anderes', 'dir', 'musste', 'du', 'durch', 'zwischen', 'nach',
           'welche', 'anderem', 'solches', 'uns', 'alle', 'aber', 'unsen',
           'habe', 'ihren', 'solcher', 'desselben', 'das', 'einer',
           'solche',
           'derselben', 'unses', 'waren', 'am', 'keinen', 'einigen', 'ihr',
           'andere', 'jenem', 'mein', 'alles', 'anderm', 'dessen', 'doch',
           'wollen', 'hatte', 'könnte', 'machen', 'ihre', 'diesem', 'haben',
           'ich', 'man', 'einmal', 'hatten', 'weiter', 'ist', 'nun',
           'ander',
           'bin', 'bist', 'einem', 'hat', 'zwar', 'anderer', 'wo', 'für',
           'jener', 'sehr', 'vor', 'selbst', 'deiner', 'welchen', 'mir',
           'jeder', 'weil', 'manchem', 'unse', 'deinen', 'mancher',
           'einiges',
           'es', 'ob', 'zu', 'einiger', 'bei', 'euch', 'jedes', 'wird',
           'aus',
           'den', 'welches', 'hab', 'sind', 'jeden', 'um', 'ihn', 'jede',
           'sonst', 'meines', 'ihres', 'gewesen', 'euer', 'dem', 'werde',
           'deinem', 'hier', 'hin', 'bis', 'sollte', 'andern', 'da',
           'nicht',
           'dazu', 'also', 'des', 'eures', 'jenes', 'und', 'oder', 'er',
           'keines', 'mich', 'welchem', 'dort', 'allen', 'an', 'meiner',
           'dasselbe', 'in', 'dich', 'keiner', 'noch', 'viel', 'vom', 'mit',
           'solchen', 'derer', 'so', 'dieser', 'meinem', 'werden', 'die',
           'diese', 'würden', 'dies', 'von'],
    'pl': ['inny', 'takze', 'jezeli', 'także', 'zeznowu', 'ktorej', 'tym',
           'lat', 'wy', 'ktorzy', 'ta', 'kto', 'moze', 'powinna', 'dlatego',
           'ktory', 'roku', 'bo', 'został', 'dość', 'mają', 'by', 'kiedy',
           'przed', 'moj', 'ponad', 'było', 'bardziej', 'mną', 'go',
           'których',
           'bez', 'jako', 'duzo', 'z', 'iz', 'acz', 'więc', 'daleko', 'on',
           'gdyz', 'sobie', 'zadnych', 'o', 'twoj', 'każdy', 'taki', 'jej',
           'bylo', 'ktos', 'ktora', 'mam', 'nich', 'że', 'ich', 'sama',
           'tylko', 'wasz', 'ja', 'mozliwe', 'może', 'dokad', 'nasz',
           'sobą',
           'musi', 'której', 'juz', 'między', 'był', 'kimś', 'moim', 'zł',
           'jaki', 'nic', 'moja', 'to', 'jakas', 'jakaś', 'która', 'deda',
           'tam', 'caly', 'byla', 'jednakze', 'czy', 'byli', 'aby', 'jakos',
           'ktorego', 'nawet', 'możliwe', 'wami', 'ku', 'nasza', 'będę',
           'jakie', 'gdzieś', 'cokolwiek', 'znów', 'niej', 'zapewne',
           'tych',
           'miedzy', 'twoje', 'niego', 'twoim', 'sposob', 'wielu', 'wasza',
           'totobą', 'naszych', 'zeby', 'kims', 'przedtem', 'wszystkie',
           'nie',
           'za', 'naszego', 'nią', 'aj', 'mnie', 'żadnych', 'was', 'ją',
           'tej',
           'wam', 'jednak', 'nas', 'soba', 'taka', 'zadna', 'ten', 'tobą',
           'gdzies', 'jedno', 'mi', 'być', 'przede', 'jeżeli', 'zaden',
           'jakkolwiek', 'nimi', 'ktore', 'którym', 'jestem', 'ma', 'pani',
           'nim', 'co', 'pana', 'natychmiast', 'zostal', 'ona', 'do', 'a',
           'wszystko', 'dziś', 'dlaczego', 'jakoś', 'po', 'dużo', 'bowiem',
           'jakiś', 'byc', 'albo', 'jakichś', 'około', 'przy', 'znow',
           'prawie', 'gdyby', 'az', 'lub', 'tego', 'dobrze', 'według',
           'była',
           'twój', 'zawsze', 'w', 'ktoś', 'niemu', 'nasze', 'teraz', 'bede',
           'wiele', 'poza', 'natomiast', 'inna', 'już', 'ktokolwiek', 'aż',
           'innych', 'moga', 'również', 'te', 'jedna', 'tutaj', 'jego',
           'gdziekolwiek', 'dzisiaj', 'sie', 'przecież', 'im', 'ciebie',
           'wszystkich', 'niz', 'pan', 'skad', 'bynajmniej', 'czemu',
           'jednakże', 'niech', 'cos', 'dwaj', 'mu', 'nasi', 'bedzie',
           'wlasnie', 'no', 'gdy', 'gdzie', 'wszystkim', 'cię', 'nad',
           'cali',
           'będzie', 'one', 'ponieważ', 'dwa', 'można', 'jesli', 'ani',
           'my',
           'jakby', 'czyli', 'na', 'przez', 'skąd', 'mozna', 'ktorych',
           'jakichs', 'żadna', 'kilka', 'od', 'alez', 'znowu', 'cały',
           'wasze',
           'dosc', 'totez', 'żaden', 'twoi', 'nami', 'swoje', 'owszem',
           'więcej', 'jest', 'którego', 'dwie', 'żeby', 'cala', 'nigdy',
           'mało', 'beda', 'były', 'u', 'przeciez', 'który', 'iż', 'wtedy',
           'mna', 'czasami', 'jakis', 'toba', 'aczkolwiek', 'jak', 'lecz',
           'mogą', 'oto', 'tak', 'zadne', 'będą', 'cała', 'pomimo', 'dokąd',
           'nam', 'moi', 'we', 'czasem', 'mój', 'kazdy', 'które', 'coś',
           'mimo', 'ono', 'cie', 'oraz', 'twym', 'powinno', 'się', 'ze',
           'sposób', 'jakiz', 'podczas', 'dzis', 'żadne', 'twoja', 'ach',
           'obok', 'moje', 'toteż', 'dla', 'niż', 'rowniez', 'ile', 'nia',
           'powinni', 'właśnie', 'poniewaz', 'pod', 'tu', 'bardzo', 'też',
           'i',
           'jakiż', 'ależ', 'ktorym', 'trzeba', 'ty', 'ale', 'sam', 'tobie',
           'jeden', 'ci', 'inne', 'byly', 'wszyscy', 'jeszcze', 'byl',
           'którzy', 'gdyż', 'są', 'jeśli', 'jemu', 'oni', 'je', 'takie',
           'powinien', 'dwoje'],
    'es': ['estuvieran', 'estuvieses', 'te', 'estuvieron', 'nos', 'estos',
           'erais', 'estaríais', 'hubiese', 'fuiste', 'tendrías',
           'estábamos',
           'habían', 'ya', 'son', 'fui', 'los', 'esté', 'fuimos', 'tenía',
           'tened', 'algo', 'han', 'seríamos', 'estuviesen', 'tus', 'suya',
           'una', 'nuestra', 'era', 'tendrás', 'sentida', 'les', 'algunos',
           'habré', 'hubieron', 'contra', 'tengo', 'estéis', 'otras',
           'quienes', 'las', 'me', 'yo', 'ha', 'como', 'ni', 'estás',
           'habíamos', 'hubieran', 'teníais', 'sentidas', 'tienen',
           'estuviéramos', 'estuviese', 'habríamos', 'tendrán', 'estuve',
           'ellos', 'sobre', 'todo', 'donde', 'vuestra', 'está', 'estamos',
           'muy', 'tienes', 'habiendo', 'mis', 'tendría', 'sin', 'fueron',
           'tenido', 'estén', 'fueran', 'desde', 'tuviésemos', 'estabais',
           'tuvieseis', 'hubiéramos', 'nuestros', 'sean', 'un', 'habremos',
           'hasta', 'estemos', 'sentidos', 'no', 'seríais', 'sea', 'eras',
           'seáis', 'tenían', 'más', 'otro', 'ellas', 'fueses', 'ese', 'os',
           'para', 'por', 'esas', 'algunas', 'hube', 'hayan', 'sería',
           'seremos', 'tuviese', 'hubieseis', 'mucho', 'fuéramos', 'le',
           'tuviéramos', 'estaría', 'estuvisteis', 'tuvieras', 'estuviera',
           'fuese', 'éramos', 'fuera', 'del', 'seamos', 'tendrían',
           'tuvieses',
           'había', 'fue', 'hayamos', 'suyas', 'poco', 'estar', 'estuvimos',
           'habrían', 'vuestro', 'hubimos', 'o', 'estoy', 'habidos', 'ti',
           'estará', 'sentido', 'él', 'suyo', 'estaré', 'hayáis', 'mi',
           'estaba', 'será', 'todos', 'esto', 'míos', 'qué', 'tanto',
           'hubo',
           'habido', 'tendríais', 'cual', 'mía', 'tengan', 'habida',
           'estado',
           'tuya', 'están', 'tuvo', 'vosostros', 'estuviésemos', 'siente',
           'fueras', 'vosostras', 'habrá', 'este', 'habríais', 'tú', 'mí',
           'sus', 'antes', 'nada', 'estarás', 'lo', 'durante', 'nosotras',
           'serás', 'se', 'pero', 'de', 'sí', 'estada', 'tuviste', 'sois',
           'habías', 'serán', 'a', 'tu', 'que', 'en', 'estabas', 'fuerais',
           'tuvieran', 'serías', 'esta', 'estarían', 'habrías', 'nuestro',
           'somos', 'uno', 'tuvimos', 'hemos', 'mías', 'eso', 'tenidos',
           'estuvieseis', 'estando', 'tuviesen', 'el', 'tuvisteis', 'tuve',
           'estas', 'soy', 'eran', 'estuviste', 'es', 'tenéis', 'mío',
           'tuyas',
           'hubisteis', 'habéis', 'hubieras', 'hubieses', 'tenemos',
           'estuvierais', 'esos', 'tenidas', 'porque', 'tenías',
           'tendremos',
           'ella', 'haya', 'sentid', 'hubierais', 'tenga', 'hubiesen',
           'vuestras', 'hubiera', 'con', 'tuyos', 'e', 'estarías',
           'fuésemos',
           'estaremos', 'estados', 'habréis', 'otros', 'estáis', 'estarán',
           'hubiésemos', 'tengáis', 'habíais', 'tuviera', 'otra', 'estaban',
           'habidas', 'nuestras', 'muchos', 'tuyo', 'tengamos', 'tuvierais',
           'vuestros', 'estaréis', 'tiene', 'esa', 'unos', 'hubiste',
           'teníamos', 'entre', 'habrán', 'al', 'seréis', 'has', 'tengas',
           'tendréis', 'quien', 'ante', 'tuvieron', 'también', 'sintiendo',
           'eres', 'tendré', 'cuando', 'fuesen', 'hay', 'estés', 'suyos',
           'serían', 'la', 'nosotros', 'estaríamos', 'estuvo', 'hayas',
           'estadas', 'habrás', 'seas', 'seré', 'fuisteis', 'tendrá', 'su',
           'tendríamos', 'teniendo', 'tenida', 'y', 'estad', 'he', 'habría',
           'fueseis', 'estuvieras'],
    'nl': ['te', 'kan', 'niets', 'wie', 'uw', 'hebben', 'zou', 'zo', 'geen',
           'wil', 'me', 'zich', 'eens', 'deze', 'nog', 'iemand', 'het',
           'mijn',
           'worden', 'door', 'dan', 'daar', 'der', 'tegen', 'over', 'kon',
           'ik', 'wezen', 'bij', 'met', 'haar', 'omdat', 'want', 'van',
           'of',
           'wat', 'was', 'een', 'ze', 'als', 'nu', 'dus', 'zal', 'heeft',
           'moet', 'zijn', 'na', 'werd', 'op', 'waren', 'hij', 'zelf',
           'dit',
           'zonder', 'andere', 'hun', 'alles', 'doch', 'uit', 'iets', 'ja',
           'reeds', 'de', 'toch', 'en', 'veel', 'tot', 'wordt', 'hoe',
           'naar',
           'zij', 'toen', 'altijd', 'ge', 'dat', 'om', 'meer', 'aan', 'had',
           'hem', 'ook', 'hier', 'mij', 'niet', 'maar', 'er', 'men', 'is',
           'voor', 'u', 'al', 'kunnen', 'in', 'ons', 'ben', 'heb', 'doen',
           'je', 'onder', 'die', 'geweest'],
    'en': ['te', 'have', 'kan', 'such', 'does', 'only', 'niets', 'hers',
           'whom', 'once', 'wie', 'uw', 'there', 'for', 'hebben', 'our',
           'yours', 'zou', 'zo', 'geen', 'wil', 'me', 'zich', 'be', 'can',
           'eens', 'deze', 'as', 'nog', 'more', 'iemand', 'why', 'het',
           'mijn',
           'between', 's', 'by', 'worden', 'during', 'that', 'into', 'door',
           'dan', 'daar', 'der', 'tegen', 'over', 'kon', 'herself', 'we',
           't',
           'ik', 'against', 'no', 'wezen', 'them', 'not', 'bij', 'met',
           'this',
           'then', 'after', 'haar', 'from', 'further', 'where', 'omdat',
           'will', 'van', 'just', 'of', 'until', 'wat', 'it', 'down', 'was',
           'een', 'other', 'if', 'which', 'are', 'most', 'als', 'because',
           'ze', 'nu', 'dus', 'below', 'zal', 'on', 'my', 'she', 'heeft',
           'moet', 'zijn', 'na', 'out', 'they', 'here', 'werd', 'too',
           'ourselves', 'op', 'hij', 'waren', 'zelf', 'am', 'theirs',
           'very',
           'dit', 'each', 'should', 'zonder', 'their', 'andere', 'hun',
           'alles', 'how', 'doch', 'both', 'uit', 'above', 'itself', 'nor',
           'iets', 'ja', 'reeds', 'de', 'and', 'while', 'at', 'ours',
           'under',
           'do', 'than', 'toch', 'a', 'en', 'about', 'veel', 'her', 'tot',
           'having', 'i', 'were', 'wordt', 'being', 'the', 'hoe',
           'themselves',
           'naar', 'zij', 'his', 'its', 'through', 'up', 'toen', 'himself',
           'altijd', 'all', 'ge', 'dat', 'myself', 'own', 'om', 'him',
           'meer',
           'aan', 'same', 'few', 'had', 'don', 'those', 'with', 'hem',
           'ook',
           'to', 'hier', 'mij', 'these', 'niet', 'did', 'any', 'doing',
           'maar',
           'again', 'er', 'men', 'is', 'yourselves', 'an', 'or', 'voor',
           'u',
           'yourself', 'has', 'in', 'what', 'who', 'but', 'al', 'ben',
           'kunnen', 'you', 'your', 'ons', 'heb', 'before', 'doen', 'off',
           'some', 'so', 'je', 'when', 'now', 'been', 'onder', 'die', 'he',
           'geweest'],
    'it': ['sui', 'sarete', 'tua', 'nostre', 'è', 'siate', 'avessimo',
           'saresti', 'avesti', 'fui', 'facesti', 'feci', 'faccio', 'non',
           'dello', 'avrà', 'sia', 'saremmo', 'avuti', 'avrete', 'nostri',
           'agli', 'una', 'era', 'coi', 'lei', 'fosti', 'sullo', 'saranno',
           'abbiate', 'suoi', 'stiate', 'facessero', 'ha', 'mia', 'fecero',
           'avuto', 'farete', 'voi', 'quelle', 'ai', 'essendo', 'sua',
           'facessi', 'stavi', 'vostre', 'eri', 'facevate', 'dell', 'nell',
           'nella', 'dov', 'avendo', 'farei', 'stessero', 'quella',
           'faceste',
           'sarebbero', 'della', 'tuo', 'avevate', 'starò', 'furono',
           'perché',
           'stavate', 'alla', 'chi', 'cui', 'per', 'ebbero', 'starete',
           'questi', 'un', 'avute', 'suo', 'starebbe', 'staremmo', 'miei',
           'nostro', 'fanno', 'di', 'avete', 'facessimo', 'allo', 'c',
           'stando', 'delle', 'avrebbero', 'facemmo', 'questa', 'negli',
           'tue',
           'fossi', 'dei', 'facevi', 'facevano', 'sugl', 'avremmo', 'sono',
           'vostra', 'loro', 'avrò', 'facciate', 'sto', 'gli', 'sta',
           'stava',
           'degl', 'avevo', 'sareste', 'faresti', 'stessimo', 'quanti',
           'avesse', 'starai', 'le', 'anche', 'fossero', 'sarà', 'nel',
           'sull',
           'fosse', 'facendo', 'avevano', 'staranno', 'del', 'hai',
           'farebbero', 'sulla', 'ed', 'quante', 'fummo', 'dalle', 'vostro',
           'avresti', 'ad', 'fu', 'ero', 'erano', 'sue', 'dalla', 'dagl',
           'l',
           'starà', 'alle', 'o', 'avreste', 'vi', 'ti', 'avessi', 'siete',
           'dal', 'queste', 'nello', 'mi', 'avrebbe', 'stetti', 'staremo',
           'stiano', 'come', 'fai', 'facevamo', 'farebbe', 'stavamo', 'che',
           'quale', 'faremo', 'stesti', 'faranno', 'ma', 'sarebbe', 'sarò',
           'lo', 'fece', 'stettero', 'se', 'facciano', 'staresti', 'agl',
           'tutto', 'sei', 'dall', 'avemmo', 'avrai', 'a', 'tu', 'ho',
           'sarei',
           'sarai', 'ebbe', 'col', 'lui', 'i', 'fossimo', 'faremmo', 'uno',
           'tutti', 'avranno', 'aveste', 'più', 'sugli', 'eravate', 'mio',
           'stavano', 'hanno', 'avremo', 'nostra', 'il', 'stareste',
           'faccia',
           'steste', 'ebbi', 'all', 'abbiano', 'stanno', 'starei', 'stesse',
           'avevamo', 'avrei', 'si', 'saremo', 'starebbero', 'nei', 'dai',
           'tuoi', 'farò', 'con', 'ci', 'e', 'avuta', 'faceva', 'stai',
           'vostri', 'abbiamo', 'nelle', 'negl', 'stessi', 'quanto',
           'dagli',
           'facciamo', 'fareste', 'da', 'farà', 'questo', 'siano', 'quanta',
           'aveva', 'avessero', 'stia', 'ne', 'dove', 'sul', 'stavo',
           'abbia',
           'avevi', 'eravamo', 'degli', 'foste', 'al', 'in', 'li', 'contro',
           'io', 'stemmo', 'facesse', 'sulle', 'tra', 'la', 'noi', 'dallo',
           'farai', 'quello', 'su', 'facevo', 'siamo', 'stiamo', 'stette',
           'mie', 'quelli'],
    'uk': ['аж', 'ви', 'де', 'до', 'за', 'зі', 'ми', 'на', 'не', 'ну', 'нх',
           'ні', 'по', 'та', 'ти', 'то', 'ту', 'ті', 'це', 'цю', 'ця', 'ці',
           'чи', 'ще', 'що', 'як', 'їй', 'їм', 'їх', 'її', 'або', 'але',
           'ало',
           'без', 'був', 'вам', 'вас', 'ваш', 'вже', 'все', 'всю', 'вся',
           'від', 'він', 'два', 'дві', 'для', 'ким', 'мож', 'моя', 'моє',
           'мої', 'міг', 'між', 'мій', 'над', 'нам', 'нас', 'наш', 'нею',
           'неї', 'них', 'ніж', 'ній', 'ось', 'при', 'про', 'під', 'пір',
           'раз', 'рік', 'сам', 'сих', 'сім', 'так', 'там', 'теж', 'тим',
           'тих', 'той', 'тою', 'три', 'тут', 'хоч', 'хто', 'цей', 'цим',
           'цих', 'час', 'щоб', 'яка', 'які', 'адже', 'буде', 'буду',
           'будь',
           'була', 'були', 'було', 'бути', 'вами', 'ваша', 'ваше', 'ваші',
           'весь', 'вниз', 'вона', 'вони', 'воно', 'всею', 'всім', 'всіх',
           'втім', 'геть', 'далі', 'двох', 'день', 'дуже', 'зате', 'його',
           'йому', 'каже', 'кого', 'коли', 'кому', 'крім', 'куди', 'лише',
           'люди', 'мало', 'мати', 'мене', 'мені', 'миру', 'мною', 'може',
           'нами', 'наша', 'наше', 'наші', 'ними', 'ніби', 'один', 'поки',
           'пора', 'рано', 'року', 'році', 'сама', 'саме', 'саму', 'самі',
           'свою', 'своє', 'свої', 'себе', 'собі', 'став', 'суть', 'така',
           'таке', 'такі', 'твоя', 'твоє', 'твій', 'тебе', 'тими', 'тобі',
           'того', 'тоді', 'тому', 'туди', 'хоча', 'хіба', 'цими', 'цієї',
           'часу', 'чого', 'чому', 'який', 'яких', 'якої', 'якщо', "ім'я",
           'інша', 'інше', 'інші', 'буває', 'будеш', 'більш', 'вгору',
           'вміти',
           'внизу', 'вісім', 'давно', 'даром', 'добре', 'довго', 'друго',
           'дякую', 'життя', 'зараз', 'знову', 'какая', 'кожен', 'кожна',
           'кожне', 'кожні', 'краще', 'ледве', 'майже', 'менше', 'могти',
           'можна', 'назад', 'немає', 'нижче', 'нього', 'однак', "п'ять",
           'перед', 'поруч', 'потім', 'проти', 'після', 'років', 'самим',
           'самих', 'самій', 'свого', 'своєї', 'своїх', 'собою', 'справ',
           'такий', 'також', 'тепер', 'тисяч', 'тобою', 'треба', 'трохи',
           'усюди', 'усіма', 'хочеш', 'цього', 'цьому', 'часто', 'через',
           'шість', 'якого', 'іноді', 'інший', 'інших', 'багато', 'будемо',
           'будете', 'будуть', 'більше', 'всього', 'всьому', 'далеко',
           'десять', 'досить', 'другий', 'дійсно', 'завжди', 'звідси',
           'зовсім', 'кругом', 'кілька', 'людина', 'можуть', 'навіть',
           'навіщо', 'нагорі', 'небудь', 'низько', 'ніколи', 'нікуди',
           'нічого', 'обидва', 'одного', 'однієї', "п'ятий", 'перший',
           'просто', 'раніше', 'раптом', 'самими', 'самого', 'самому',
           'сказав', 'скрізь', 'сьомий', 'третій', 'тільки', 'хотіти',
           'чотири', 'чудово', 'шостий', 'близько', 'важлива', 'важливе',
           'важливі', 'вдалині', 'восьмий', 'говорив', "дев'ять", 'десятий',
           'зайнята', 'зайнято', 'зайняті', 'занадто', 'значить', 'навколо',
           'нарешті', 'нерідко', 'повинно', 'посеред', 'початку', 'пізніше',
           'сказала', 'сказати', 'скільки', 'спасибі', 'частіше',
           'важливий',
           'двадцять', "дев'ятий", 'зазвичай', 'зайнятий', 'звичайно',
           'здається', 'найбільш', 'не', 'можна', 'недалеко', 'особливо',
           'потрібно', 'спочатку', 'сьогодні', 'численна', 'численне',
           'численні', 'відсотків', 'двадцятий', 'звідусіль', 'мільйонів',
           'нещодавно', 'прекрасно', 'четвертий', 'численний', 'будь',
           'ласка',
           'дванадцять', 'одинадцять', 'сімнадцять', 'тринадцять',
           'безперервно', 'дванадцятий', 'одинадцятий', 'одного', 'разу',
           "п'ятнадцять", 'сімнадцятий', 'тринадцятий', 'шістнадцять',
           'вісімнадцять', "п'ятнадцятий", 'чотирнадцять', 'шістнадцятий',
           'вісімнадцятий', "дев'ятнадцять", 'чотирнадцятий',
           "дев'ятнадцятий"],
    'hu': ['elsõ', 'jobban', 'míg', 'jó', 'vannak', 'cikkek', 'amelyet',
           'azután', 'egész', 'ill', 'volna', 'mindent', 'belül', 'õket',
           'ugyanis', 'ezt', 'azon', 'amelynek', 'ezen', 'igen', 'õ',
           'elég',
           'tehát', 'cikk', 'amelyekben', 'miért', 'mely', 'éppen', 'abban',
           'volt', 'be', 'elõször', 'vagyis', 'eddig', 'nekem', 'vagy',
           'minden', 'arra', 'amelyeket', 'azonban', 'saját', 'való', 's',
           'azzal', 'kívül', 'újra', 'akkor', 'így', 'amely', 'vissza',
           'semmi', 'néha', 'aztán', 'utolsó', 'mindenki', 'ehhez', 'más',
           'úgy', 'rá', 'valami', 'egyéb', 'ebben', 'legyen', 'nélkül',
           'számára', 'ott', 'utána', 'nagyobb', 'van', 'kellett', 'ezért',
           'általában', 'vagyok', 'felé', 'már', 'és', 'egyetlen',
           'mellett',
           'voltunk', 'vele', 'most', 'melyek', 'valaki', 'maga', 'fel',
           'õk',
           'voltam', 'ilyenkor', 'mikor', 'sokkal', 'mintha', 'még',
           'viszont',
           'kell', 'több', 'ezek', 'mindig', 'másik', 'ahol', 'mi', 'ami',
           'közül', 'mivel', 'persze', 'sok', 'amelyek', 'hogyan', 'itt',
           'tovább', 'csak', 'amit', 'aki', 'keresztül', 'ahhoz', 'hiszen',
           'szinte', 'cikkeket', 'ennek', 'de', 'milyen', 'neki', 'egyre',
           'a',
           'emilyen', 'lenne', 'amíg', 'elõtt', 'én', 'talán', 'nincs',
           'valamint', 'amikor', 'egyik', 'el', 'azt', 'egy', 'után',
           'benne',
           'szerint', 'illetve', 'sem', 'teljes', 'lesz', 'nagy', 'mert',
           'az',
           'ilyen', 'szemben', 'akik', 'e', 'hogy', 'amolyan', 'között',
           'át',
           'pedig', 'meg', 'voltak', 'alatt', 'arról', 'elõ', 'lehet',
           'legalább', 'azok', 'keressünk', 'ne', 'azért', 'ez', 'bár',
           'jól',
           'lenni', 'nagyon', 'egyes', 'ekkor', 'össze', 'ezzel', 'ison',
           'lehetett', 'magát', 'erre', 'sokat', 'mit', 'új', 'mint',
           'néhány',
           'által', 'ismét', 'majd', 'ki', 'hanem', 'ahogy', 'nem', 'ellen',
           'ill.', 'olyan', 'továbbá', 'újabb', 'annak', 'lett'],
    'ar': ['فى', 'في', 'كل', 'لم', 'لن', 'له', 'من', 'هو', 'هي', 'قوة',
           'كما', 'لها', 'منذ', 'وقد', 'ولا', 'لقاء', 'مقابل', 'هناك',
           'وقال', 'وكان', 'وقالت', 'وكانت', 'فيه', 'لكن', 'وفي', 'ولم',
           'ومن', 'وهو', 'وهي', 'يوم', 'فيها', 'منها', 'يكون', 'يمكن',
           'حيث', 'االا', 'اما', 'االتى', 'التي', 'اكثر', 'ايضا', 'الذى',
           'الذي', 'الان', 'الذين', 'ابين', 'ذلك', 'دون', 'حول', 'حين',
           'الى', 'انه', 'اول', 'انها', 'ف', 'و', 'و6', 'قد', 'لا', 'ما',
           'مع', 'هذا', 'واحد', 'واضاف', 'واضافت', 'فان', 'قبل', 'قال',
           'كان', 'لدى', 'نحو', 'هذه', 'وان', 'واكد', 'كانت', 'واوضح',
           'ب',
           'ا', 'أ', '،', 'عن', 'عند', 'عندما', 'على', 'عليه', 'عليها',
           'تم', 'ضد', 'بعد', 'بعض', 'حتى', 'اذا', 'احد', 'بان', 'اجل',
           'غير', 'بن', 'به', 'ثم', 'اف', 'ان', 'او', 'اي', 'بها']}
